# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(Version.MajorMinor)$(Rev:.r)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  
  Version.MajorMinor: 1.0.0

steps:

- task: Cake@0
  inputs:
    script: 'build.cake'
    target: 'Default'
    arguments: '-configuration=$(buildConfiguration)'
    verbosity: 'Verbose'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/*.csproj'
    arguments: '-c Release -r win10-x64 -o ./publish'
    feedsToUse: 'select'
    versioningScheme: 'byBuildNumber'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'

